# Generated by Django 4.0.8 on 2025-08-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relation_ship',
            field=models.TextField(blank=True, choices=[('Father', 'Padre'), ('Mother', 'Madre'), ('Brother', 'Hermano'), ('Sister', 'Hermana'), ('Grand mother', 'Abuela'), ('Grand father', 'Abuelo'), ('Other', 'Otro')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachelor', 'Licenciatura'), ('Master', 'Maestría')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
