# Generated by Django 4.0.8 on 2025-08-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_summary_es_course_summary_fr_course_title_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_ru',
        ),
    ]
