# Generated by Django 4.0.8 on 2025-08-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_summary_en_remove_course_summary_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('desarrollo_profesional', 'Desarrollo Profesional y Liderazgo'), ('tecnologia', 'Tecnología e Innovación'), ('gestion_empresarial', 'Gestión Empresarial'), ('marketing_ventas', 'Marketing y Ventas'), ('recursos_humanos', 'Recursos Humanos'), ('finanzas', 'Finanzas y Contabilidad'), ('operaciones', 'Operaciones y Logística'), ('comunicacion', 'Comunicación y Relaciones Públicas'), ('salud_bienestar', 'Salud y Bienestar'), ('educacion', 'Educación y Capacitación'), ('otros', 'Otros')], default='otros', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.BooleanField(default=False, help_text='¿El curso incluye certificación?'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duración del curso', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('horas', 'Horas'), ('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses')], default='horas', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='¿El curso está activo y disponible?'),
        ),
        migrations.AddField(
            model_name='course',
            name='materials_included',
            field=models.TextField(blank=True, help_text='Materiales incluidos en el curso', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(blank=True, help_text='Número máximo de estudiantes', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='methodology',
            field=models.TextField(blank=True, help_text='Metodología de enseñanza', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='modality',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('e-learning', 'E-learning'), ('hibrido', 'Híbrido'), ('intensivo', 'Intensivo')], default='presencial', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.TextField(blank=True, help_text='Lista de objetivos específicos del curso', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Requisitos previos para tomar el curso', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Descripción del público objetivo', null=True),
        ),
    ]
