# Generated by Django 4.0.8 on 2025-08-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_category_course_certification_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen representativa del curso (recomendado: 800x600px)', null=True, upload_to='course_images/%Y/%m/%d/'),
        ),
    ]
