# Generated by Django 4.0.8 on 2025-08-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_lessonblock_quizblock_quizblockquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Color de fondo del bloque', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='height',
            field=models.CharField(default='auto', help_text='Alto del bloque (ej: auto, 300px)', max_length=10),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el bloque está activo'),
        ),
    ]
