# Generated by Django 4.0.8 on 2025-08-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_choice_choice_es_choice_choice_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_en',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_fr',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_ru',
        ),
    ]
