# Generated by Django 4.0.8 on 2025-08-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_newsandevents_summary_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen opcional para la noticia o evento', null=True, upload_to='news_events/'),
        ),
    ]
