# Generated by Django 4.0.8 on 2025-08-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newsandevents_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='posted_as',
            field=models.CharField(choices=[('Noticia', 'Noticia'), ('Evento', 'Evento')], max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero')], max_length=10),
        ),
    ]
